"""revision created3

Revision ID: 763f4a2dbc72
Revises: 1a57edc79562
Create Date: 2026-09-16 02:39:18.638831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763f4a2dbc72'
down_revision: Union[str, Sequence[str], None] = '1a57edc79562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_masks', 'url')
    op.drop_column('image_masks', 'filename')
    op.drop_column('image_masks', 'extension')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_masks', sa.Column('extension', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('image_masks', sa.Column('filename', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('image_masks', sa.Column('url', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
